import { supabase } from "../supabaseClient.js";
import { getState } from "../core/state.js";
import { AppCore } from "../core/appCore.js";
import { inviteMember } from "../auth/invitations.js";

export async function listClients(){const s=getState();const {data,error}=await supabase.from("clients").select("*").eq("agency_id",s.agency.id).is("archived_at",null).order("name");if(error)throw error;return data||[];}
export async function createClientCompany({name,email,notes}){const s=getState();const {data,error}=await supabase.from("clients").insert({agency_id:s.agency.id,name:name.trim(),contact_email:email||null,notes:notes||null,created_by:s.user.id}).select().single();if(error)throw error;return data;}
export async function renderClientsView(container){AppCore.ui.renderLoading(container,"Loading clients…");try{const clients=await listClients();container.replaceChildren();const root=document.createElement("section");root.className="ap-admin-view";const head=document.createElement("div");head.className="ap-admin-view__header";const h=document.createElement("div");h.innerHTML="<h2>Clients</h2><p>Companies and portal access.</p>";const add=button("New client","primary");add.addEventListener("click",()=>openClientForm(null,()=>renderClientsView(container)));head.append(h,add);root.append(head);const grid=document.createElement("div");grid.className="ap-card-grid";for(const client of clients){const card=document.createElement("article");card.className="ap-card";const title=document.createElement("h3");title.textContent=client.name;const email=document.createElement("p");email.textContent=client.contact_email||"No primary email";const actions=document.createElement("div");actions.className="ap-row-actions";const invite=button("Invite contact","secondary");invite.classList.add("ap-btn--sm");invite.addEventListener("click",()=>openInvite(client));const edit=button("Edit","ghost");edit.classList.add("ap-btn--sm");edit.addEventListener("click",()=>openClientForm(client,()=>renderClientsView(container)));const archive=button("Archive","ghost");archive.classList.add("ap-btn--sm");archive.addEventListener("click",async()=>{if(!await AppCore.ui.confirm({title:"Archive client?",message:"Client portal access will stop immediately.",confirmLabel:"Archive",danger:true}))return;try{const {error}=await supabase.from("clients").update({archived_at:new Date().toISOString()}).eq("id",client.id);if(error)throw error;renderClientsView(container);}catch(err){AppCore.ui.toast(AppCore.ui.describeError(err),"error");}});actions.append(invite,edit,archive);card.append(title,email,actions);grid.append(card);}if(!clients.length)AppCore.ui.renderEmpty(grid,{title:"No clients yet",message:"Create a client company to share folders with them.",actionLabel:"New client",onAction:()=>openClientForm(null,()=>renderClientsView(container))});root.append(grid);container.append(root);}catch(error){AppCore.ui.renderError(container,error,()=>renderClientsView(container));}}
function openClientForm(client,done){const form=document.createElement("form");form.className="ap-stack";const name=input("Company name"),email=input("Primary email","email",false),notes=document.createElement("textarea");notes.className="ap-textarea";notes.placeholder="Notes";name.value=client?.name||"";email.value=client?.contact_email||"";notes.value=client?.notes||"";const save=button(client?"Save":"Create","primary");save.type="submit";form.append(name,email,notes,save);form.addEventListener("submit",async e=>{e.preventDefault();save.disabled=true;try{if(client){const {error}=await supabase.from("clients").update({name:name.value.trim(),contact_email:email.value||null,notes:notes.value||null}).eq("id",client.id);if(error)throw error;}else await createClientCompany({name:name.value,email:email.value,notes:notes.value});AppCore.ui.closeModal();done();}catch(err){AppCore.ui.toast(AppCore.ui.describeError(err),"error");}finally{save.disabled=false;}});AppCore.ui.openModal({title:client?"Edit client":"New client",content:form,actions:[]});name.focus();}
function openInvite(client){const form=document.createElement("form");form.className="ap-stack";const email=input("Client email","email");email.value=client.contact_email||"";const submit=button("Create invitation","primary");submit.type="submit";const result=document.createElement("div");result.className="ap-invite-result";form.append(email,submit,result);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{const inv=await inviteMember({email:email.value,role:"client",clientId:client.id});result.replaceChildren();const label=document.createElement("p");label.textContent="Copy this invitation link:";const code=document.createElement("code");code.textContent=inv.link;const copy=button("Copy link","secondary");copy.type="button";copy.addEventListener("click",()=>navigator.clipboard.writeText(inv.link).then(()=>AppCore.ui.toast("Invitation link copied.","success")));result.append(label,code,copy);}catch(err){AppCore.ui.toast(AppCore.ui.describeError(err),"error");}finally{submit.disabled=false;}});AppCore.ui.openModal({title:`Invite to ${client.name}`,content:form,actions:[]});}
function input(placeholder,type="text",required=true){const x=document.createElement("input");x.className="ap-input";x.placeholder=placeholder;x.type=type;x.required=required;return x;}
function button(text,variant){const b=document.createElement("button");b.className=`ap-btn ap-btn--${variant}`;b.type="button";b.textContent=text;return b;}
