import { restoreAuth, signOut } from "./auth/auth.js";
import { getState, setState } from "./core/state.js";
import { emit } from "./core/events.js";
import { activateAgency } from "./workspace/agencies.js";
import { renderFolderTree } from "./workspace/folderTree.js";
import { renderBreadcrumb, selectFolder } from "./workspace/folders.js";
import { selectModule, unmountActiveModule } from "./core/moduleRegistry.js";
import { mountGlobalSearch } from "./modules/search.js";
import { AppCore } from "./core/appCore.js";
import { renderHome, renderTasksHub, renderInvoicesHub, renderLibrary, renderInbox, renderFolderOverview, renderProfileView } from "./views/portalViews.js";

let currentView = "home";
function renderIdentity() {
  const s = getState(); const host = document.getElementById("agency-identity"); host.replaceChildren();
  const img = document.createElement("img"); img.className = "ap-workspace-logo"; img.alt = ""; if (s.agency.logo_url) img.src = s.agency.logo_url; else img.hidden = true;
  const name = document.createElement("strong"); name.className = "ap-client-workspace-name"; name.textContent = s.agency.name; host.append(img, name);
  const user = document.getElementById("user-menu"); user.replaceChildren(); const trigger = document.createElement("button"); trigger.type = "button"; trigger.className = "ap-profile-trigger";
  const avatar = document.createElement("span"); avatar.className = "ap-profile-avatar"; avatar.textContent = AppCore.utils.initials(s.profile?.full_name || s.user.email);
  const label = document.createElement("span"); label.textContent = s.profile?.full_name || s.user.email; trigger.append(avatar, label, document.createTextNode("⌄"));
  const menu = document.createElement("div"); menu.className = "ap-profile-menu"; menu.hidden = true;
  const profile = document.createElement("button"); profile.type = "button"; profile.textContent = "Profile"; profile.addEventListener("click", () => showView("profile"));
  const out = document.createElement("button"); out.type = "button"; out.textContent = "Log out"; out.addEventListener("click", signOut); menu.append(profile, out); trigger.addEventListener("click", () => menu.hidden = !menu.hidden); user.append(trigger, menu);
}
function hideChrome(){document.getElementById("page-header").hidden=true;document.getElementById("module-tabs").hidden=true;}
function showModuleChrome(){document.getElementById("page-header").hidden=false;document.getElementById("module-tabs").hidden=true;renderBreadcrumb();}
function mark(view){document.querySelectorAll("[data-global-view]").forEach(b=>b.classList.toggle("ap-rail-item--active",b.dataset.globalView===view||(view==="my-tasks"&&b.dataset.globalView==="tasks")));document.querySelectorAll("[data-workspace-view]").forEach(b=>b.classList.toggle("ap-workspace-link--active",b.dataset.workspaceView===view));document.querySelectorAll("[data-library-view]").forEach(b=>b.classList.toggle("ap-library-nav__active",view===`library-${b.dataset.libraryView}`));}
async function showView(view, noHash=false){currentView=view;await unmountActiveModule();setState({selectedModule:null,selectedFolderId:null});renderFolderTree();hideChrome();mark(view);const content=document.getElementById("module-content");content.classList.remove("ap-inbox-page");const ctx=AppCore.getModuleContext();if(view==="home")await renderHome(content,ctx);else if(view==="inbox")await renderInbox(content,ctx);else if(view==="my-tasks")await renderTasksHub(content,ctx,{mineOnly:true});else if(view==="tasks")await renderTasksHub(content,ctx,{mineOnly:true});else if(view==="invoices")await renderInvoicesHub(content,ctx);else if(view==="profile")renderProfileView(content,ctx,{onBack:()=>showView("home"),onLogout:signOut});else if(view.startsWith("library-"))await renderLibrary(content,ctx,view.slice(8));if(!noHash)history.replaceState(null,"",`#/${view}`);}
async function showFolder(id){currentView="folder";await unmountActiveModule();setState({selectedModule:null,selectedFolderId:id});hideChrome();mark("folder");renderFolderTree();await renderFolderOverview(document.getElementById("module-content"),AppCore.getModuleContext(),id);history.replaceState(null,"",`#/folder/${id}`);}
function bind(){document.querySelectorAll("#module-tabs [data-module]").forEach(b=>b.addEventListener("click",()=>selectModule(b.dataset.module)));document.querySelector(".ap-library-toggle")?.addEventListener("click",()=>{const t=document.querySelector(".ap-library-toggle"),n=document.querySelector(".ap-library-nav"),open=t.getAttribute("aria-expanded")!=="false";t.setAttribute("aria-expanded",String(!open));n.hidden=open;});document.querySelectorAll("[data-workspace-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.workspaceView)));document.querySelectorAll("[data-library-view]").forEach(b=>b.addEventListener("click",()=>showView(`library-${b.dataset.libraryView}`)));document.querySelectorAll("[data-global-view]").forEach(b=>b.addEventListener("click",()=>{const v=b.dataset.globalView;showView(v);}));document.getElementById("back-to-folder")?.addEventListener("click",()=>{const id=getState().selectedFolderId;if(id)showFolder(id);});document.getElementById("sidebar-toggle").addEventListener("click",()=>document.body.classList.toggle("ap-sidebar-open"));document.getElementById("sidebar-backdrop").addEventListener("click",()=>document.body.classList.remove("ap-sidebar-open"));document.addEventListener("folder:selected",e=>{renderFolderTree();renderBreadcrumb();document.body.classList.remove("ap-sidebar-open");if(e.detail?.folderId&&!e.detail?.skipOverview)showFolder(e.detail.folderId);else if(!e.detail?.folderId&&currentView==="folder")showView("home");});document.addEventListener("module:mounted",showModuleChrome);document.addEventListener("inbox:close",()=>showView("home"));document.addEventListener("keydown",e=>{if(e.key==="Escape"){document.body.classList.remove("ap-sidebar-open");document.getElementById("inbox-panel").classList.remove("ap-inbox-panel--open");}});}
async function boot(){try{const session=await restoreAuth("client");if(!session){location.replace("login.html");return;}const memberships=getState().memberships.filter(m=>m.role==="client");if(!memberships.length){location.replace("index.html");return;}const remembered=localStorage.getItem("ap.lastAgencyId");const member=memberships.find(m=>m.agency_id===remembered)||memberships[0];await activateAgency(member.agency_id);if(getState().role!=="client"){location.replace("index.html");return;}bind();renderIdentity();renderFolderTree();renderBreadcrumb();await mountGlobalSearch(AppCore.getModuleContext());setState({ready:true});emit("app:ready",{agencyId:getState().agency.id,userId:getState().user.id,role:getState().role,surface:"client"});const hash=location.hash;const fm=hash.match(/^#\/folder\/([0-9a-f-]+)$/i);const mm=hash.match(/^#\/f\/([0-9a-f-]+)\/(conversation|boards|docs|files|invoices)$/i);if(mm&&getState().folders.some(f=>f.id===mm[1])){await selectFolder(mm[1],{skipOverview:true});await selectModule(mm[2]);}else if(fm&&getState().folders.some(f=>f.id===fm[1]))await selectFolder(fm[1]);else if(/^#\/library-/.test(hash))await showView(hash.slice(2),true);else if(["#/home","#/inbox","#/my-tasks","#/tasks","#/invoices","#/profile"].includes(hash))await showView(hash.slice(2),true);else await showView("home");}catch(error){console.error(error);AppCore.ui.renderError(document.getElementById("module-content"),error,()=>location.reload());}}
boot();
