import { restoreAuth, signIn, signUp, requestPasswordReset, updatePassword, loadIdentity } from "./auth/auth.js";
import { getState } from "./core/state.js";
import { completeProfile, createAgency } from "./auth/onboarding.js";
import { acceptInvitation } from "./auth/invitations.js";
import { AppCore } from "./core/appCore.js";

const root=document.getElementById("auth-root");
const params=new URLSearchParams(location.search);const inviteToken=params.get("invite");const resetMode=params.get("mode")==="reset";
function el(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!=null)x.textContent=text;return x;}
function input(label,type="text",value=""){const wrap=el("label","ap-field");const span=el("span","ap-field__label",label);const control=el("input","ap-input");control.type=type;control.value=value;control.required=true;wrap.append(span,control);return{wrap,control};}
function authCard(title,subtitle){root.replaceChildren();const card=el("section","ap-auth-card");card.append(el("div","ap-auth-logo","CO"),el("h1","ap-auth-title",title),el("p","ap-auth-subtitle",subtitle||""));root.append(card);return card;}
function message(text,variant="info"){const d=el("div",`ap-inline-message ap-inline-message--${variant}`,text);return d;}
function routeAfterLogin(){const s=getState();if(!s.profile?.full_name){showProfile();return;}if(!s.memberships.length){showAgency();return;}const staff=s.memberships.some(m=>["owner","team"].includes(m.role));location.replace(staff?"index.html":"client-view.html");}
async function handleExisting(){if(inviteToken&&getState().session){showInvitation();return;}if(resetMode&&getState().session){showReset();return;}if(getState().session){routeAfterLogin();return;}showSignIn();}
function showSignIn(){const card=authCard("Welcome to The Workspace","Enter your email and password, or log in with email.");const form=el("form","ap-auth-form");const email=input("Email address","email",params.get("email")||"");const pass=input("Password","password");const submit=el("button","ap-btn ap-btn--primary","Log in");submit.type="submit";const switcher=el("div","ap-auth-links");const signup=el("button","ap-link-btn","Create account");signup.type="button";signup.addEventListener("click",showSignUp);const forgot=el("button","ap-link-btn","Forgot password?");forgot.type="button";forgot.addEventListener("click",showForgot);switcher.append(signup,forgot);form.append(email.wrap,pass.wrap,submit,switcher);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{await signIn(email.control.value,pass.control.value);if(inviteToken)showInvitation();else routeAfterLogin();}catch(err){form.prepend(message(AppCore.ui.describeError(err),"error"));}finally{submit.disabled=false;}});card.append(form);}
function showSignUp(){const card=authCard("Create your account",inviteToken?"Create an account, verify your email, then reopen the invitation link.":"Start an agency workspace.");const form=el("form","ap-auth-form");const name=input("Full name");const email=input("Email","email",params.get("email")||"");const pass=input("Password","password");pass.control.minLength=8;const submit=el("button","ap-btn ap-btn--primary","Create account");submit.type="submit";const back=el("button","ap-link-btn","Already have an account? Sign in");back.type="button";back.addEventListener("click",showSignIn);form.append(name.wrap,email.wrap,pass.wrap,submit,back);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{const data=await signUp(email.control.value,pass.control.value,name.control.value);if(data.session){await loadIdentity();inviteToken?showInvitation():routeAfterLogin();}else{const c=authCard("Check your inbox","Confirm your email address, then return here to continue.");c.append(message("Email verification is required before your workspace can be created.","success"));}}catch(err){form.prepend(message(AppCore.ui.describeError(err),"error"));}finally{submit.disabled=false;}});card.append(form);}
function showForgot(){const card=authCard("Reset your password","We'll send a recovery link to your email.");const form=el("form","ap-auth-form");const email=input("Email","email");const submit=el("button","ap-btn ap-btn--primary","Send reset link");submit.type="submit";const back=el("button","ap-link-btn","Back to sign in");back.type="button";back.addEventListener("click",showSignIn);form.append(email.wrap,submit,back);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{await requestPasswordReset(email.control.value);form.replaceChildren(message("Password reset email sent.","success"),back);}catch(err){form.prepend(message(AppCore.ui.describeError(err),"error"));}finally{submit.disabled=false;}});card.append(form);}
function showReset(){const card=authCard("Choose a new password","Use at least 8 characters.");const form=el("form","ap-auth-form");const pass=input("New password","password");pass.control.minLength=8;const submit=el("button","ap-btn ap-btn--primary","Update password");submit.type="submit";form.append(pass.wrap,submit);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{await updatePassword(pass.control.value);params.delete("mode");history.replaceState(null,"",location.pathname);await loadIdentity();routeAfterLogin();}catch(err){form.prepend(message(AppCore.ui.describeError(err),"error"));}finally{submit.disabled=false;}});card.append(form);}
function showProfile(){const card=authCard("Complete your profile","Tell your team and clients who you are.");const form=el("form","ap-auth-form");const name=input("Full name","text",getState().profile?.full_name||"");const submit=el("button","ap-btn ap-btn--primary","Continue");submit.type="submit";form.append(name.wrap,submit);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{await completeProfile(name.control.value);inviteToken?showInvitation():(getState().memberships.length?routeAfterLogin():showAgency());}catch(err){form.prepend(message(AppCore.ui.describeError(err),"error"));}finally{submit.disabled=false;}});card.append(form);}
function showAgency(){const card=authCard("Create your workspace","This becomes your agency's private project hub.");const form=el("form","ap-auth-form");const name=input("Agency name");const submit=el("button","ap-btn ap-btn--primary","Create workspace");submit.type="submit";form.append(name.wrap,submit);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{await createAgency(name.control.value);location.replace("index.html");}catch(err){form.prepend(message(AppCore.ui.describeError(err),"error"));}finally{submit.disabled=false;}});card.append(form);}
function showInvitation(){const card=authCard("Join workspace","Accept this invitation using the account that received it.");const accept=el("button","ap-btn ap-btn--primary","Accept invitation");accept.addEventListener("click",async()=>{accept.disabled=true;try{const result=await acceptInvitation(inviteToken);await loadIdentity();location.replace(result?.role==="client"?"client-view.html":"index.html");}catch(err){card.append(message(AppCore.ui.describeError(err),"error"));accept.disabled=false;}});card.append(accept);}
(async()=>{try{await restoreAuth("login");await handleExisting();}catch(error){const card=authCard("Unable to start","Check your Supabase configuration and connection.");card.append(message(AppCore.ui.describeError(error),"error"));}})();
