import { supabase } from "../supabaseClient.js";
import { getState } from "../core/state.js";

const BUCKET="conversation-attachments";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

export async function signedAttachmentUrl(path){const {data,error}=await supabase.storage.from(BUCKET).createSignedUrl(path,3600);if(error)throw error;return data.signedUrl;}
export async function listReviewComments(attachmentId){const {data,error}=await supabase.from("media_review_comments").select("*,author:profiles!media_review_comments_author_id_fkey(id,full_name,email,avatar_url)").eq("attachment_id",attachmentId).order("created_at",{ascending:true});if(error)throw error;return data||[];}
export async function addReviewComment({attachmentId,body,x=null,y=null,time=null}){const s=getState();const {data,error}=await supabase.from("media_review_comments").insert({agency_id:s.agency.id,attachment_id:attachmentId,author_id:s.user.id,body:body.trim(),x_percent:x,y_percent:y,time_seconds:time}).select().single();if(error)throw error;return data;}
export async function deleteReviewComment(id){const {error}=await supabase.from("media_review_comments").delete().eq("id",id);if(error)throw error;}

export async function openImageReview(attachment,{onChanged}={}){
  let comments=[]; let pinMode=false; let pending=null;
  const url=await signedAttachmentUrl(attachment.storage_path);
  const overlay=document.createElement("div"); overlay.className="k-review-overlay";
  overlay.innerHTML=`<header class="k-review-top"><div><strong>${esc(attachment.original_name)}</strong><small>Image review · ${Math.round((attachment.size_bytes||0)/1024)} KB</small></div><div class="k-review-top__actions"><a class="k-review-open" href="${esc(url)}" target="_blank" rel="noopener">Open original</a><button class="k-review-close" type="button" aria-label="Close">×</button></div></header><div class="k-review-body"><main class="k-review-stage"><div class="k-review-toolbar"><button class="k-review-pin-btn" type="button">▣ Add pin</button><span>Choose Add pin, then click the detail you want to discuss.</span></div><div class="k-review-canvas"><div class="k-review-image-wrap"><img alt="${esc(attachment.original_name)}"></div></div></main><aside class="k-review-side"><div class="k-review-side__head"><h2>Review comments</h2><span class="k-review-count"></span></div><div class="k-review-comments"></div><form class="k-review-general"><textarea placeholder="Add a general comment…" maxlength="5000"></textarea><button type="submit">Comment</button></form></aside></div>`;
  document.body.append(overlay); document.body.classList.add("k-review-opened");
  const img=overlay.querySelector("img"), wrap=overlay.querySelector(".k-review-image-wrap"), list=overlay.querySelector(".k-review-comments"), count=overlay.querySelector(".k-review-count"), pinBtn=overlay.querySelector(".k-review-pin-btn"); img.src=url;
  const close=()=>{overlay.remove();document.body.classList.remove("k-review-opened");}; overlay.querySelector(".k-review-close").onclick=close; overlay.addEventListener("keydown",e=>{if(e.key==="Escape")close();}); overlay.tabIndex=-1; overlay.focus();
  async function refresh(){try{comments=await listReviewComments(attachment.id);render();onChanged?.();}catch(e){list.innerHTML=`<div class="k-review-error">${esc(e.message||e)}</div>`;}}
  function render(){wrap.querySelectorAll(".k-review-pin").forEach(n=>n.remove()); count.textContent=`${comments.length} comment${comments.length===1?"":"s"}`; list.replaceChildren(); if(!comments.length){const empty=document.createElement("div");empty.className="k-review-empty";empty.textContent="No comments yet. Pin a detail or add a general comment.";list.append(empty);} comments.forEach((c,i)=>{if(c.x_percent!=null&&c.y_percent!=null){const p=document.createElement("button");p.type="button";p.className="k-review-pin";p.style.left=`${c.x_percent}%`;p.style.top=`${c.y_percent}%`;p.textContent=String(i+1);p.title=c.body;p.onclick=()=>document.getElementById(`review-comment-${c.id}`)?.scrollIntoView({behavior:"smooth",block:"center"});wrap.append(p);} const card=document.createElement("article");card.className="k-review-comment";card.id=`review-comment-${c.id}`;const who=c.author?.full_name||c.author?.email||"User";card.innerHTML=`<div class="k-review-comment__meta"><strong>${esc(who)}</strong><span>${new Date(c.created_at).toLocaleString()}</span></div>${c.x_percent!=null?`<div class="k-review-comment__pinlabel">Pin ${i+1}</div>`:""}<p>${esc(c.body)}</p>`; if(c.author_id===getState().user.id){const del=document.createElement("button");del.type="button";del.className="k-review-delete";del.textContent="Delete";del.onclick=async()=>{await deleteReviewComment(c.id);await refresh();};card.append(del);}list.append(card);});}
  pinBtn.onclick=()=>{pinMode=!pinMode;pinBtn.classList.toggle("is-active",pinMode);wrap.classList.toggle("is-pinning",pinMode);};
  wrap.addEventListener("click",e=>{if(!pinMode||e.target!==img)return;const r=img.getBoundingClientRect();pending={x:((e.clientX-r.left)/r.width)*100,y:((e.clientY-r.top)/r.height)*100};const dialog=document.createElement("div");dialog.className="k-review-pin-dialog";dialog.innerHTML=`<div><strong>Comment on this detail</strong><textarea maxlength="5000" placeholder="What should be changed?"></textarea><div><button type="button" data-cancel>Cancel</button><button type="button" data-save>Save comment</button></div></div>`;overlay.append(dialog);dialog.querySelector("textarea").focus();dialog.querySelector("[data-cancel]").onclick=()=>dialog.remove();dialog.querySelector("[data-save]").onclick=async()=>{const body=dialog.querySelector("textarea").value.trim();if(!body)return;const b=dialog.querySelector("[data-save]");b.disabled=true;try{await addReviewComment({attachmentId:attachment.id,body,x:pending.x,y:pending.y});dialog.remove();pinMode=false;pinBtn.classList.remove("is-active");wrap.classList.remove("is-pinning");await refresh();}catch(err){alert(err.message||err);b.disabled=false;}};});
  overlay.querySelector(".k-review-general").onsubmit=async e=>{e.preventDefault();const ta=e.currentTarget.querySelector("textarea"),body=ta.value.trim();if(!body)return;const b=e.currentTarget.querySelector("button");b.disabled=true;try{await addReviewComment({attachmentId:attachment.id,body});ta.value="";await refresh();}catch(err){alert(err.message||err);}finally{b.disabled=false;}};
  await refresh();
}


const fmtTime=value=>{const total=Math.max(0,Math.floor(Number(value)||0));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60),sec=total%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`:`${m}:${String(sec).padStart(2,"0")}`;};

export async function openVideoReview(attachment,{onChanged}={}){
  let comments=[]; let pinMode=false;
  const url=await signedAttachmentUrl(attachment.storage_path);
  const overlay=document.createElement("div"); overlay.className="k-review-overlay k-video-review-overlay";
  overlay.innerHTML=`<header class="k-review-top"><div><strong>${esc(attachment.original_name)}</strong><small>Video review · pause anywhere, then pin the exact detail</small></div><div class="k-review-top__actions"><a class="k-review-open" href="${esc(url)}" target="_blank" rel="noopener">Open original</a><button class="k-review-close" type="button" aria-label="Close">×</button></div></header><div class="k-review-body"><main class="k-review-stage"><div class="k-review-toolbar"><button class="k-review-pin-btn" type="button">▣ Add pin</button><span class="k-video-review-hint">Pause the video, choose Add pin, then click the detail you want changed.</span></div><div class="k-review-canvas"><div class="k-review-video-wrap"><video controls preload="metadata" playsinline></video></div></div></main><aside class="k-review-side"><div class="k-review-side__head"><h2>Review comments</h2><span class="k-review-count"></span></div><div class="k-review-comments"></div><form class="k-review-general"><textarea placeholder="Add a general video comment…" maxlength="5000"></textarea><button type="submit">Comment</button></form></aside></div>`;
  document.body.append(overlay); document.body.classList.add("k-review-opened");
  const video=overlay.querySelector("video"),wrap=overlay.querySelector(".k-review-video-wrap"),list=overlay.querySelector(".k-review-comments"),count=overlay.querySelector(".k-review-count"),pinBtn=overlay.querySelector(".k-review-pin-btn"),hint=overlay.querySelector(".k-video-review-hint"); video.src=url;
  const close=()=>{video.pause();overlay.remove();document.body.classList.remove("k-review-opened");}; overlay.querySelector(".k-review-close").onclick=close; overlay.addEventListener("keydown",e=>{if(e.key==="Escape")close();}); overlay.tabIndex=-1;overlay.focus();
  async function refresh(){try{comments=await listReviewComments(attachment.id);render();onChanged?.();}catch(e){list.innerHTML=`<div class="k-review-error">${esc(e.message||e)}</div>`;}}
  function render(){wrap.querySelectorAll(".k-review-pin").forEach(n=>n.remove());count.textContent=`${comments.length} comment${comments.length===1?"":"s"}`;list.replaceChildren();if(!comments.length){const empty=document.createElement("div");empty.className="k-review-empty";empty.textContent="No comments yet. Pause the video and pin a detail, or add a general comment.";list.append(empty);}comments.forEach((c,i)=>{const hasPin=c.x_percent!=null&&c.y_percent!=null;if(hasPin&&c.time_seconds!=null&&Math.abs(video.currentTime-Number(c.time_seconds))<0.4){const p=document.createElement("button");p.type="button";p.className="k-review-pin";p.style.left=`${c.x_percent}%`;p.style.top=`${c.y_percent}%`;p.textContent=String(i+1);p.title=c.body;p.onclick=()=>document.getElementById(`review-comment-${c.id}`)?.scrollIntoView({behavior:"smooth",block:"center"});wrap.append(p);}const card=document.createElement("article");card.className="k-review-comment";card.id=`review-comment-${c.id}`;const who=c.author?.full_name||c.author?.email||"User";card.innerHTML=`<div class="k-review-comment__meta"><strong>${esc(who)}</strong><span>${new Date(c.created_at).toLocaleString()}</span></div>${c.time_seconds!=null?`<button type="button" class="k-review-time" data-time="${Number(c.time_seconds)}">▶ ${fmtTime(c.time_seconds)}</button>`:""}${hasPin?`<div class="k-review-comment__pinlabel">Pin ${i+1}</div>`:""}<p>${esc(c.body)}</p>`;card.querySelector(".k-review-time")?.addEventListener("click",e=>{video.pause();video.currentTime=Number(e.currentTarget.dataset.time);setTimeout(render,60);});if(c.author_id===getState().user.id){const del=document.createElement("button");del.type="button";del.className="k-review-delete";del.textContent="Delete";del.onclick=async()=>{await deleteReviewComment(c.id);await refresh();};card.append(del);}list.append(card);});}
  video.addEventListener("timeupdate",()=>{if(video.paused)render();}); video.addEventListener("seeked",render); video.addEventListener("pause",()=>{hint.textContent=`Paused at ${fmtTime(video.currentTime)} — choose Add pin, then click the exact detail.`;render();});video.addEventListener("play",()=>{pinMode=false;pinBtn.classList.remove("is-active");wrap.classList.remove("is-pinning");hint.textContent="Pause the video first to add a pin comment.";wrap.querySelectorAll(".k-review-pin").forEach(n=>n.remove());});
  pinBtn.onclick=()=>{if(!video.paused){video.pause();hint.textContent=`Paused at ${fmtTime(video.currentTime)} — now click Add pin again.`;return;}pinMode=!pinMode;pinBtn.classList.toggle("is-active",pinMode);wrap.classList.toggle("is-pinning",pinMode);hint.textContent=pinMode?`Click the exact detail at ${fmtTime(video.currentTime)}.`:`Paused at ${fmtTime(video.currentTime)} — choose Add pin when ready.`;};
  wrap.addEventListener("click",e=>{if(!pinMode||e.target!==video)return;const r=video.getBoundingClientRect();const pending={x:((e.clientX-r.left)/r.width)*100,y:((e.clientY-r.top)/r.height)*100,time:video.currentTime};const dialog=document.createElement("div");dialog.className="k-review-pin-dialog";dialog.innerHTML=`<div><strong>Comment at ${fmtTime(pending.time)}</strong><textarea maxlength="5000" placeholder="What should be changed here?"></textarea><div><button type="button" data-cancel>Cancel</button><button type="button" data-save>Save comment</button></div></div>`;overlay.append(dialog);dialog.querySelector("textarea").focus();dialog.querySelector("[data-cancel]").onclick=()=>dialog.remove();dialog.querySelector("[data-save]").onclick=async()=>{const body=dialog.querySelector("textarea").value.trim();if(!body)return;const b=dialog.querySelector("[data-save]");b.disabled=true;try{await addReviewComment({attachmentId:attachment.id,body,x:pending.x,y:pending.y,time:pending.time});dialog.remove();pinMode=false;pinBtn.classList.remove("is-active");wrap.classList.remove("is-pinning");await refresh();}catch(err){alert(err.message||err);b.disabled=false;}};});
  overlay.querySelector(".k-review-general").onsubmit=async e=>{e.preventDefault();const ta=e.currentTarget.querySelector("textarea"),body=ta.value.trim();if(!body)return;const b=e.currentTarget.querySelector("button");b.disabled=true;try{await addReviewComment({attachmentId:attachment.id,body,time:video.currentTime});ta.value="";await refresh();}catch(err){alert(err.message||err);}finally{b.disabled=false;}};
  await refresh();
}
