import { AppCore } from "../core/appCore.js";
import { on, emit } from "../core/events.js";
import { subscribeChannel, unsubscribeByPrefix } from "../core/realtime.js";
import { listConversations, createConversation, updateConversation } from "../conversations/conversations.js";
import { listMessages, sendMessage, deleteMessage } from "../conversations/messages.js";

const state={container:null,context:null,conversations:[],activeId:null,messages:[],off:[],replyTo:null,timer:null};
const el=(tag,cls,text)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(text!=null)x.textContent=text;return x;};
async function load(){if(!state.context.folderId){AppCore.ui.renderEmpty(state.container,{title:"Choose a folder",message:"Select a folder to open its conversation."});return;}AppCore.ui.renderLoading(state.container,"Loading conversations…");try{state.conversations=await listConversations(state.context.folderId);if(!state.conversations.some(c=>c.id===state.activeId))state.activeId=state.conversations[0]?.id||null;await loadMessages();render();subscribe();}catch(error){AppCore.ui.renderError(state.container,error,load);}}
async function loadMessages(){state.messages=state.activeId?await listMessages(state.activeId):[];}
function subscribe(){unsubscribeByPrefix("messages:conversation:");unsubscribeByPrefix("conversations:folder:");if(state.activeId)subscribeChannel(`messages:conversation:${state.activeId}`,ch=>ch.on("postgres_changes",{event:"*",schema:"public",table:"messages",filter:`conversation_id=eq.${state.activeId}`},()=>schedule()));if(state.context.folderId)subscribeChannel(`conversations:folder:${state.context.folderId}`,ch=>ch.on("postgres_changes",{event:"*",schema:"public",table:"conversations",filter:`folder_id=eq.${state.context.folderId}`},()=>schedule()));}
function schedule(){clearTimeout(state.timer);state.timer=setTimeout(()=>load().catch(console.error),120);}
function render(){const root=el("section","ap-conversation");root.dataset.module="conversation";const side=el("aside","ap-conversation__list");const sideHead=el("div","ap-conversation__list-header");sideHead.append(el("h2","","Conversations"));if(state.context.isStaff){const b=el("button","ap-btn ap-btn--primary ap-btn--sm","New");b.type="button";b.addEventListener("click",openCreate);sideHead.append(b);}side.append(sideHead);for(const c of state.conversations){const b=el("button",`ap-conversation__thread${c.id===state.activeId?" ap-conversation__thread--active":""}`,c.title);b.type="button";b.addEventListener("click",async()=>{state.activeId=c.id;await loadMessages();subscribe();render();});side.append(b);}const main=el("div","ap-conversation__main");const current=state.conversations.find(c=>c.id===state.activeId);if(!current){const empty=el("div","ap-empty");empty.append(el("h3","",state.context.isClient?"No conversation has been shared yet":"No conversations yet"),el("p","",state.context.isClient?"Messages shared with you will appear here.":"Start a conversation in this folder."));main.append(empty);}else{const header=el("div","ap-conversation__header");header.append(el("h2","",current.title));if(state.context.isStaff){const settings=el("button","ap-btn ap-btn--ghost ap-btn--sm","Settings");settings.type="button";settings.addEventListener("click",()=>openSettings(current));header.append(settings);}main.append(header);const feed=el("div","ap-message-feed");for(const msg of state.messages)feed.append(renderMessage(msg));main.append(feed,renderComposer(current));queueMicrotask(()=>feed.scrollTop=feed.scrollHeight);}root.append(side,main);state.container.replaceChildren(root);}
function renderMessage(msg){const mine=msg.sender_id===state.context.user.id;const card=el("article",`ap-message${mine?" ap-message--mine":""}${!msg.client_visible?" ap-message--internal":""}`);const meta=el("div","ap-message__meta");meta.append(el("strong","",msg.sender?.full_name||msg.sender?.email||"Member"),el("span","",AppCore.utils.formatDate(msg.created_at,"relative")));if(!msg.client_visible&&state.context.isStaff)meta.append(el("span","ap-badge ap-badge--warning","Internal"));const body=el("p","ap-message__body",msg.body);const actions=el("div","ap-message__actions");const reply=el("button","ap-btn ap-btn--ghost ap-btn--sm","Reply");reply.type="button";reply.addEventListener("click",()=>{state.replyTo=msg.reply_to_message_id||msg.id;render();});actions.append(reply);if(mine||state.context.isOwner){const del=el("button","ap-btn ap-btn--ghost ap-btn--sm","Delete");del.type="button";del.addEventListener("click",async()=>{if(await AppCore.ui.confirm({title:"Delete message?",message:"This cannot be undone.",confirmLabel:"Delete",danger:true})){try{await deleteMessage(msg.id);await loadMessages();render();}catch(e){AppCore.ui.toast(AppCore.ui.describeError(e),"error");}}});actions.append(del);}card.append(meta,body,actions);return card;}
function renderComposer(current){const form=el("form","ap-message-composer");if(state.replyTo){const bar=el("div","ap-replying","Replying to a message");const cancel=el("button","ap-btn ap-btn--ghost ap-btn--sm","Cancel");cancel.type="button";cancel.addEventListener("click",()=>{state.replyTo=null;render();});bar.append(cancel);form.append(bar);}const textarea=el("textarea","ap-textarea");textarea.placeholder="Write a message…";textarea.required=true;textarea.maxLength=20000;const bottom=el("div","ap-message-composer__bottom");let visible=null;if(state.context.isStaff){const label=el("label","ap-checkbox-label");visible=document.createElement("input");visible.type="checkbox";visible.checked=true;label.append(visible,document.createTextNode(" Visible to client"));bottom.append(label);}const send=el("button","ap-btn ap-btn--primary","Send");send.type="submit";bottom.append(send);form.append(textarea,bottom);form.addEventListener("submit",async e=>{e.preventDefault();send.disabled=true;try{await sendMessage({conversationId:current.id,body:textarea.value,clientVisible:state.context.isClient?true:(visible?.checked??true),replyToMessageId:state.replyTo});state.replyTo=null;textarea.value="";await loadMessages();render();emit("data:changed",{entity:"message",entityId:null,folderId:state.context.folderId,action:"created"});}catch(err){AppCore.ui.toast(AppCore.ui.describeError(err),"error");}finally{send.disabled=false;}});return form;}
function openCreate(){const form=el("form","ap-stack");const title=el("input","ap-input");title.placeholder="Conversation title";title.required=true;const label=el("label","ap-checkbox-label");const visible=document.createElement("input");visible.type="checkbox";label.append(visible,document.createTextNode(" Visible to clients"));const save=el("button","ap-btn ap-btn--primary","Create");save.type="submit";form.append(title,label,save);form.addEventListener("submit",async e=>{e.preventDefault();try{const c=await createConversation({folderId:state.context.folderId,title:title.value,clientVisible:visible.checked});state.activeId=c.id;AppCore.ui.closeModal();await load();emit("data:changed",{entity:"conversation",entityId:c.id,folderId:state.context.folderId,action:"created"});}catch(err){AppCore.ui.toast(AppCore.ui.describeError(err),"error");}});AppCore.ui.openModal({title:"New conversation",content:form,actions:[]});title.focus();}
function openSettings(c){const form=el("form","ap-stack");const title=el("input","ap-input");title.value=c.title;const label=el("label","ap-checkbox-label");const visible=document.createElement("input");visible.type="checkbox";visible.checked=c.client_visible;label.append(visible,document.createTextNode(" Visible to clients"));const save=el("button","ap-btn ap-btn--primary","Save");save.type="submit";const archive=el("button","ap-btn ap-btn--danger","Archive");archive.type="button";archive.addEventListener("click",async()=>{try{await updateConversation(c.id,{archived_at:new Date().toISOString()});AppCore.ui.closeModal();state.activeId=null;await load();}catch(err){AppCore.ui.toast(AppCore.ui.describeError(err),"error");}});form.append(title,label,save,archive);form.addEventListener("submit",async e=>{e.preventDefault();try{await updateConversation(c.id,{title:title.value.trim(),client_visible:visible.checked});AppCore.ui.closeModal();await load();}catch(err){AppCore.ui.toast(AppCore.ui.describeError(err),"error");}});AppCore.ui.openModal({title:"Conversation settings",content:form,actions:[]});}
const module={name:"conversation",async mount(container,context){state.container=container;state.context=context;state.off=[on("folder:selected",()=>{})];await load();},async unmount(){state.off.forEach(fn=>fn());state.off=[];unsubscribeByPrefix("messages:conversation:");unsubscribeByPrefix("conversations:folder:");clearTimeout(state.timer);state.container?.replaceChildren();state.container=null;},async refresh(context){state.context=context;state.activeId=null;await load();}};
export default module;
